### ISSUE TITLE
Quantum Compressors don't work with custom recipes and catalysts at all in 1.6.1

### ISSUE THREAD

**Issue by Atricos** [OmnifactoryDevs/ExtendedCrafting#17]
**Description:**
After updating from 1.6.0 to 1.6.1, existing recipes added in `config/extendedcrafting` under `S:custom_singularities` with a custom catalyst under `S:default_catalyst` do not work anymore. We tried the workarounds in this report (https://github.com/OmnifactoryDevs/ExtendedCrafting/issues/7), but couldn't make it work.

**Steps to reproduce:**
1. Add some custom Singularities like
  `100;clay;minecraft:clay_ball;AEBCCF`
2. Add a custom catalyst (in Divine Journey 2, we have a custom item - not sure if this affects the outcome) 
  `S:default_catalyst=contenttweaker:singularification_catalyst:0`
3. Launch the game.
4. Try to craft it - it doesn't consume the input item.

(We're not sure if updating from 1.6.0 to 1.6.1 caused this or not. It's possble that Singularities added in 1.6.0 do not work in 1.6.1 anymore.)
 
**Pictures:**
![image](https://user-images.githubusercontent.com/24854267/135484600-0e2bce89-f9b1-4d7c-bc4a-006e1ac18565.png)
![image](https://user-images.githubusercontent.com/24854267/135484622-8ddf6e39-5021-4ddd-a343-98e371de9329.png)

At least the recipe is beign recognized, because the Singularity icon does show up at the top:
![image](https://user-images.githubusercontent.com/24854267/135484694-c8f8917f-2857-4c9e-bfa0-273cac850ba1.png)

**Comment by Exaxxion** [comment]
Thank you for reporting this bug.

Per PR #18, this bug has apparently been present since 1.6.0.6 and is not related to the most recent changes to Singularities (localization support) from 1.6.0.7/1.6.1. Updating directly from 1.6.0 to 1.6.1 this would be the first time you'd have encountered this issue.

The nature of this issue is that a recipe for the current ingredient stack is being sought out only when the Compressor's cached last-valid-ingredient is "nothing", due to an inadvertent placement of the recipe lookup code within a check rather than immediately following that check.

I'll verify the PR shortly and there will be a new beta build 1.6.1.1 on CurseForge published with the fix shortly after it's merged.
