### ISSUE TITLE
OreDict item in ingredient invisible in JEI

### ISSUE THREAD

**Issue by Krutoy242** [OmnifactoryDevs/ExtendedCrafting#3]
Recipe was unchanged before i update from old Extended Crafting. Now `<ore:blockAethium>` is invisible as ingredient, but item still craftable if i put right items in empty slots:

<img src="https://i.imgur.com/jOW8obZ.gif" width=300>

I check and this item is OreDicted normally 
<img src="https://i.imgur.com/4yCBuqP.png" width=200>

Recipe
```java
	var blockAethium = <ore:blockAethium>;
	recipes.remove(<environmentaltech:void_ore_miner_cont_6>);
	mods.extendedcrafting.TableCrafting.addShaped(0, <environmentaltech:void_ore_miner_cont_6>, 
	[[blockAethium, <ic2:iridium_reflector>, blockAethium], 
	[<ic2:nuclear:10>, <environmentaltech:void_ore_miner_cont_5>, <ic2:nuclear:10>], 
	[blockAethium, <ic2:iridium_reflector>, blockAethium]]);  
```

**Comment by Exaxxion** [comment]
I'd like to get some more information to focus in on the underlying problem.



First, what version of CraftTweaker and the accompanying *Tweaker addons are you using?

Second, let's establish some context:
Are any other items registered under `blockAethium` in the ore dictionary?
Does this still happen if you specify the Aethium Block item directly rather than the ore dictionary bracket handler?
Does this occur just with Aethium recipes or is it reproducible with other recipes using oredict bracket handlers?
Does the recipe function properly if you use the vanilla crafting table shaped recipe function rather than the ExC one?

**Comment by eutropius225** [comment]
The issue is that Environmental Tech (and other mods apparently) register their items to the oredict after CraftTweaker scripts have run.

As the following script shows, `<ore:blockAethium>` does not contain any items when the script is run:

```zs
var blockAethium = <ore:blockAethium>;

blockAethium.add(<minecraft:cobblestone>); // test item

print("Printing <ore:blockAethium> items...");

for stack in blockAethium.items {
    print(stack.commandString);
}

print("Finished printing items.");
```
appears in the log with:
```zs
[INITIALIZATION][CLIENT][INFO] Adding Cobblestone to ore dictionary entry blockAethium
[INITIALIZATION][CLIENT][INFO] Printing <ore:blockAethium> items...
[INITIALIZATION][CLIENT][INFO] <minecraft:cobblestone>
[INITIALIZATION][CLIENT][INFO] Finished printing items.
```

This caused issues because [matching items were resolved when the ingredient was constructed](https://github.com/OmnifactoryDevs/ExtendedCrafting/blob/2d4cec0cae20d3116b038d367ef1881eb2049e26/src/main/java/com/blakebr0/extendedcrafting/compat/crafttweaker/CraftTweakerUtils.java#L47).

The solution was to use the overlooked [CraftTweakerMC#getIngredient](https://github.com/CraftTweaker/CraftTweaker/blob/4d9e91e563b8bce2b22db24a7f83e1d6c01b6da5/CraftTweaker2-MC1120-Main/src/main/java/crafttweaker/api/minecraft/CraftTweakerMC.java#L610) which does everything necessary.

**Comment by Krutoy242** [comment]
Yeah, probably working fine now! Thanks!


<img src="https://i.imgur.com/05NGcKn.png">
